name: vdc_incomes_and_expenses
description: A app to help the incomes and expenses control.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^5.0.2
  freezed: ^2.0.3+1
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo-footer.png

  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Light.ttf
          weight: 300
        - asset: assets/fonts/Rajdhani-Regular.ttf
        - asset: assets/fonts/Rajdhani-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rajdhani-Bold.ttf
          weight: 700
